import { leagueSpartan, openSans } from "@/styles/fonts";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/custom-ui/navbar/navbar";
import RecentBlogWrapper from "@/components/custom-ui/blog/recent-blog-wrapper/recent-blog-wrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${openSans.variable} bg-neutrals-50 font-league-spartan antialiased`}
      >
        <Navbar />
        <div className="mx-auto flex w-full max-w-[108rem] flex-col items-center gap-16 px-4 py-10 lg:px-12">
          {/* Div with the grid will be removed on pr approval */}
          {/* <div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3">
            {Array.from({ length: 9 }).map((_, index) => (
              <Card
                key={index}
                image={"/card/basic-techniques.jpg"}
                time="2 days ago"
                title="Osnovne tehnike penjanja za pocetnike"
                description="Penjanje može delovati zastrašujuće za početnike, ali uz prave tehnike, brzo ćete savladati osnove. U ovom članku istražujemo ključne veštine koje vam trebaju da biste bezbedno i efikasno započeli svoju penjačku avanturu, bilo da penjete u prirodi ili na veštačkoj steni."
                tags={["Penjanje", "Boulder", "fleksibilnost"]}
              />
            ))}
          </div> */}
          <RecentBlogWrapper />
          {/* {children} */}
        </div>
      </body>
    </html>
  );
}
