import { leagueSpartan, openSans } from "@/styles/fonts";
import "./globals.css";
import type { Metadata } from "next";
import Navbar from "@/components/custom-ui/navbar/navbar";
import {
  BenefitsCard,
  BenefitsForAdults,
  BenefitsForChildren,
  BenefitsSection,
} from "@/components/custom-ui/benefits";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${openSans.variable} bg-neutrals-50 font-league-spartan antialiased`}
      >
        <Navbar />
        <div className="mx-auto flex w-full max-w-[108rem] flex-col items-center gap-16 px-4 pb-10 lg:px-12">
          <BenefitsSection title="Benefiti penjanja za odrasle">
            {BenefitsForAdults.map((data, index) => (
              <BenefitsCard
                key={index}
                title={data.title}
                description={data.description}
                image={data.image}
              />
            ))}
          </BenefitsSection>
          <BenefitsSection title="Benefiti penjanja za djecu">
            {BenefitsForChildren.map((data, index) => (
              <BenefitsCard
                key={index}
                title={data.title}
                description={data.description}
                image={data.image}
              />
            ))}
          </BenefitsSection>
          {/* {children} */}
        </div>
      </body>
    </html>
  );
}
